services:
  jdict:
    build: .
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - /mnt/appdata/jdict/data:/app/data
      - /mnt/appdata/jdict/wiki:/app/wiki
      - /mnt/appdata/jdict/sources:/app/sources
    restart: unless-stopped
